version: 0.2

env:
  variables:
     # key: "value"
     # key: "value"
     MYSQL_USER: "admin"	
     MYSQL_HOST:	"db1.cdcey7nbdoev.us-east-1.rds.amazonaws.com"	
     MYSQL_PASSWORD:	"admin123"	
     MYSQL_ROOT_PASSWORD: "admin123"	
     db_port: "3306"	
     MYSQL_DATABASE: "mysql"
  
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      # name: version
      # name: version
      python: 3.8

  build:
    commands:
      # - command
      #  - command
      #    - export FLASK_APP = app.py
           - pip3 install -r requirements.txt  
  
artifacts:
   files:
     - scripts/*.sh
     - appspec.yml
   discard-paths: yes
   
